name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *" # Exécution quotidienne à minuit UTC
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Automated daily update" > update-log.txt
          date >> update-log.txt

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Automated daily update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
